### ISSUE TITLE
I'm not sure where to put something like this

### ISSUE THREAD

**Issue by dbwww** [lerichardson/clack#3]
You or someone else needs to rewrite the code in a Windows form app instead.  Or, recreate it in C /C++ via Win32 API.  I'd be willing to do this but I don't want to do all of this just for the pull request to get rejected.  LMK

**Comment by lerichardson** [comment]
Oh, windows forms. WPF, or just Windows Forms?

**Comment by dbwww** [comment]
Either one, really.  But since the form apps interact directly with Win32 I would use that

**Comment by lerichardson** [comment]
Are you taking about the file saving? In that case, just read [this](https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-save-a-file-with-a-picker)

**Comment by dbwww** [comment]
no, I am talking about using windows built in api to create a new window, aka Win32 API

**Comment by lerichardson** [comment]
Oh I see, Ok. I haven't looked into windows forms to much. Does it use xaml?

**Comment by lerichardson** [comment]
I think you can go ahead with this.
